### ISSUE TITLE
erro da tabela cliente

### ISSUE THREAD

**Issue by vbarbarulo** [awspark/new_aws_master#2]
![google-logo-high-res](https://cloud.githubusercontent.com/assets/7585792/6670888/44956308-cbe0-11e4-8ba0-ecb1953c5664.png)
Esta dando erro quando vou salvar os dados da empresa

**Comment by vbarbarulo** [comment]
Ola esta dando erro aqui

**Comment by awsyspark** [comment]
Ola vou falar alguma coisa aqui só para te mostrar que esta errado. 
kkkkkk

**Comment by awsyspark** [comment]
aaaaaa

**Comment by awsyspark** [comment]
vvvvvv

**Comment by vbarbarulo** [comment]
https://github.com/awspark/new_aws_master/labels/bug
