### ISSUE TITLE
Clientes

### ISSUE THREAD

**Issue by awsyspark** [awspark/new_aws_master#4]
Deu esse erro quando tentei salvar segue a imagem com o erro 
![google-logo-high-res](https://cloud.githubusercontent.com/assets/9676737/6671437/e0100dbc-cbe3-11e4-823c-c7fb437ec6d6.png)

E ai me fala o que é?

**Comment by vbarbarulo** [comment]
Ok esse erro ja foi corrigido, doi um alteração do banco de dados, que estava dando um erro.
